#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("customer_client.Resource", IsApplication=true)]

namespace customer_client
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::customer_client.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::customer_client.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::customer_client.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int BasicDing = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int burger = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int citrus = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int facebook = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int facebook2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icecream = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int lorem = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int lorem2 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int OrangeLogo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int pizza = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int QBLogo = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int soda = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int water = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000d
			public const int Description = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int Thumbnail = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int Title = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int addButton = 2131034116;
			
			// aapt resource value: 0x7f05001a
			public const int addItemButton = 2131034138;
			
			// aapt resource value: 0x7f05001c
			public const int backToMenu = 2131034140;
			
			// aapt resource value: 0x7f050021
			public const int contentFrame = 2131034145;
			
			// aapt resource value: 0x7f050002
			public const int description = 2131034114;
			
			// aapt resource value: 0x7f05001e
			public const int dingBut = 2131034142;
			
			// aapt resource value: 0x7f05000f
			public const int emailAddress = 2131034127;
			
			// aapt resource value: 0x7f050008
			public const int enterTableNumber = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int foodName = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int getGRCode = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int getTableHeader = 2131034118;
			
			// aapt resource value: 0x7f050012
			public const int guestLogin = 2131034130;
			
			// aapt resource value: 0x7f050001
			public const int image = 2131034113;
			
			// aapt resource value: 0x7f050014
			public const int imageButton1 = 2131034132;
			
			// aapt resource value: 0x7f05000a
			public const int imageView1 = 2131034122;
			
			// aapt resource value: 0x7f050016
			public const int itemListView = 2131034134;
			
			// aapt resource value: 0x7f050018
			public const int label = 2131034136;
			
			// aapt resource value: 0x7f050015
			public const int linearLayout1 = 2131034133;
			
			// aapt resource value: 0x7f050013
			public const int login = 2131034131;
			
			// aapt resource value: 0x7f050019
			public const int nameEditText = 2131034137;
			
			// aapt resource value: 0x7f05001b
			public const int orderTable = 2131034139;
			
			// aapt resource value: 0x7f050011
			public const int password = 2131034129;
			
			// aapt resource value: 0x7f050003
			public const int price = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int relativeLayout1 = 2131034117;
			
			// aapt resource value: 0x7f05001f
			public const int res1But = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int res2But = 2131034144;
			
			// aapt resource value: 0x7f050009
			public const int tableSubmit = 2131034121;
			
			// aapt resource value: 0x7f05000e
			public const int textView1 = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int textView2 = 2131034128;
			
			// aapt resource value: 0x7f05001d
			public const int total = 2131034141;
			
			// aapt resource value: 0x7f050017
			public const int viewOrder = 2131034135;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int detail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int getTable = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ListViewItemRow = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int menuOrder = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int menuOrderBak = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int orderTable = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int resSelect = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int zxingscanneractivitylayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int zxingscannerfragmentlayout = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
