#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("customer_client.Resource", IsApplication=true)]

namespace customer_client
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::customer_client.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::customer_client.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int facebook = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int facebook2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int lorem = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int lorem2 = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050011
			public const int addItemButton = 2131034129;
			
			// aapt resource value: 0x7f050014
			public const int dingBut = 2131034132;
			
			// aapt resource value: 0x7f050007
			public const int editText1 = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int editText2 = 2131034121;
			
			// aapt resource value: 0x7f050003
			public const int enterTableNumber = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int getGRCode = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int getTableHeader = 2131034113;
			
			// aapt resource value: 0x7f05000b
			public const int imageButton1 = 2131034123;
			
			// aapt resource value: 0x7f050005
			public const int imageView1 = 2131034117;
			
			// aapt resource value: 0x7f05000d
			public const int itemListView = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int label = 2131034127;
			
			// aapt resource value: 0x7f05000c
			public const int linearLayout1 = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int login = 2131034122;
			
			// aapt resource value: 0x7f050010
			public const int nameEditText = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int orderTable = 2131034130;
			
			// aapt resource value: 0x7f050000
			public const int relativeLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int tableSubmit = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int textView1 = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int textView2 = 2131034120;
			
			// aapt resource value: 0x7f050013
			public const int total = 2131034131;
			
			// aapt resource value: 0x7f05000e
			public const int viewOrder = 2131034126;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int getTable = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int menuOrder = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int menuOrderBak = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int orderTable = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
